# Generated by Django 6.1 on 2026-10-07 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=127, null=True)),
                ('is_included', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=127, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=127, null=True)),
                ('rooms', models.CharField(blank=True, max_length=127, null=True)),
                ('parking', models.BooleanField(blank=True, max_length=127, null=True)),
                ('backyard', models.CharField(blank=True, max_length=127, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('0', 'آپارتمان'), ('1', 'ویلا'), ('1', 'تجاری'), ('1', 'اداری'), ('1', 'زمین')], max_length=1, null=True)),
                ('deal_type', models.CharField(blank=True, choices=[('0', 'خرید'), ('1', 'اجاره')], max_length=1, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('Attributes', models.ManyToManyField(to='base.attribute')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.city')),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
