# Generated by Django 6.1 on 2026-08-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
