# Generated by Django 6.1 on 2026-10-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_attribute_city_remove_product_category_property_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='area',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
